version: '3.2'

services:

  localtunnel:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: " --local-host <your_host> --port 8080 --subdomain <your_subdomain>"